### Create a Customer
POST http://localhost:3000/
Content-Type: application/json

{
  "fullname": "Dharun Prakash J A",
  "username": "dp",
  "password": "123",
  "aadhaar": 123456789122120,
  "pan": "DHARUN1234",
  "contact": 123456789,
  "email": "dharun@gmail.com"
}

### Get All Customers
GET http://localhost:3000/

### Get Customer by ID
GET http://localhost:3000/6798e4cf099ff42db761e9b5

### Update Customer by ID
PUT http://localhost:3000/
Content-Type: application/json

{
  "_id": "6798e4cf099ff42db761e9b5",
  "fullname": "Dharun",
  "username": "dp",
  "password": "123",
  "aadhaar": 1234567890,
  "pan": "DHARUN1234",
  "contact": 123456789,
  "email": "dharun@gmail.com",
  "__v": 0
}

### Delete Customer by ID
DELETE http://localhost:3000/6798e4cf099ff42db761e9b5

### GET CUSTOMER BY AADHAR 

GET http://localhost:3000/aadhar/123456789122120
