########################################## CUSTOMER ###############################################################
### GET CUSTOMER
GET http://localhost:5000/customer
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YTc2MWI1ZjEzMjQyMjk1MDA2ZGFiZCIsInVzZXJuYW1lIjoic2VsdmFfMSIsImlhdCI6MTczOTAyMjc3NCwiZXhwIjoxNzM5MDI2Mzc0fQ.q7izjqSlqrvjifejBFQpz8KUxLNkseY_GT13XU-fHXE
###
POST http://localhost:5000/customer
Content-Type: application/json

{
  "fullname": "DHARUN PRAKASH J A",
  "username": "dharun_1",
  "password": "123456789",
  "aadhaar": 9012399120,
  "pan": "dha1234",
  "contact": 6374406703,
  "email": "dharunprakash2904@gmail.com"
}

### GET CUSTOMER BY ID 
GET http://localhost:5000/customer/67a5d4b03440b2d7b7b422c8
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YTcxMDlhMGM2ZDNmNjYxOGM3ZDAzOCIsInVzZXJuYW1lIjoidmV0cmVlXzEiLCJpYXQiOjE3MzkwMDIwMTEsImV4cCI6MTczOTAwNTYxMX0.gGelAIJoQz61ZNYne71Yvh1GjGlFuKJs7QRgG28aJk0

### UPDATE CUSTOMER BY ID
PUT http://localhost:5000/customer
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YTZmZjcxZWJjZmRmMmIzNzAzYzllNiIsInVzZXJuYW1lIjoibGVuaW4zIiwiaWF0IjoxNzM4OTk3NjE3LCJleHAiOjE3MzkwMDEyMTd9.gIPey1epNElfPcLm1y_-I28RslZDg4_TQecZHwv8ngw

{
  "_id": "67a5c8e36a8d94dc1cd12cba",
  "fullname": "Selva",
  "username": "dp",
  "password": "123",
  "aadhaar": 1234567890,
  "pan": "DHARUN1234",
  "contact": 6374406703,
  "email": "dharun@gmail.com",
  "__v": 0
}

### DELETE CUSTOMER BY ID 
DELETE http://localhost:5000/customer/67a5d6a456a3295b5718bde4
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YTZmZjcxZWJjZmRmMmIzNzAzYzllNiIsInVzZXJuYW1lIjoibGVuaW4zIiwiaWF0IjoxNzM4OTk3NjE3LCJleHAiOjE3MzkwMDEyMTd9.gIPey1epNElfPcLm1y_-I28RslZDg4_TQecZHwv8ngw

### GET CUSTOMER BY AADHAR
GET http://localhost:5000/customer/aadhar/987654321
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YTZmZjcxZWJjZmRmMmIzNzAzYzllNiIsInVzZXJuYW1lIjoibGVuaW4zIiwiaWF0IjoxNzM4OTk3NjE3LCJleHAiOjE3MzkwMDEyMTd9.gIPey1epNElfPcLm1y_-I28RslZDg4_TQecZHwv8ngw

### GET CUSTOMER BY USERNAME 
GET http://localhost:5000/customer/username/V3
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YTZmZjcxZWJjZmRmMmIzNzAzYzllNiIsInVzZXJuYW1lIjoibGVuaW4zIiwiaWF0IjoxNzM4OTk3NjE3LCJleHAiOjE3MzkwMDEyMTd9.gIPey1epNElfPcLm1y_-I28RslZDg4_TQecZHwv8ngw

########################################## ACCOUNT ###############################################################
### GET ALL ACCOUNT WITH CARD
GET http://localhost:5000/account
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YTc3MDE0YjY1MDIxMTUxYzY1ZDUzOSIsInVzZXJuYW1lIjoiZGhhcnVuXzEiLCJpYXQiOjE3MzkwMjY0NTIsImV4cCI6MTczOTAzMDA1Mn0.A-6WnPcoRadccy0MeJ6uoF5cDB2Mo2286E0-A_jD1vM
### ADD Bank Account
POST http://localhost:5000/account
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YTc2MWI1ZjEzMjQyMjk1MDA2ZGFiZCIsInVzZXJuYW1lIjoic2VsdmFfMSIsImlhdCI6MTczOTAyMjc3NCwiZXhwIjoxNzM5MDI2Mzc0fQ.q7izjqSlqrvjifejBFQpz8KUxLNkseY_GT13XU-fHXE


{
    "username": "dharun_1",
    "accountNumber": 999000,
    "accountBalance": 100000,
    "accountStatus": "active"
}

### GET ACCOUNT BY ID
GET http://localhost:5000/account/67a5e55651341ae5ed4177f8
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YTZmZjcxZWJjZmRmMmIzNzAzYzllNiIsInVzZXJuYW1lIjoibGVuaW4zIiwiaWF0IjoxNzM4OTk3NjE3LCJleHAiOjE3MzkwMDEyMTd9.gIPey1epNElfPcLm1y_-I28RslZDg4_TQecZHwv8ngw


### UPDATE ACCOUNT BY ID
PUT http://localhost:5000/account/67a5e55651341ae5ed4177f8
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YTcxMDlhMGM2ZDNmNjYxOGM3ZDAzOCIsInVzZXJuYW1lIjoidmV0cmVlXzEiLCJpYXQiOjE3MzkwMDIwMTEsImV4cCI6MTczOTAwNTYxMX0.gGelAIJoQz61ZNYne71Yvh1GjGlFuKJs7QRgG28aJk0


{
  "username": "vetree_1",
  "accountNumber": 123456789,
  "accountBalance": 1000,
  "__v": 0
}

### DELETE ACCOUNT BY ID
DELETE http://localhost:5000/account/67a5e55651341ae5ed4177f8
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YTZmZjcxZWJjZmRmMmIzNzAzYzllNiIsInVzZXJuYW1lIjoibGVuaW4zIiwiaWF0IjoxNzM4OTk3NjE3LCJleHAiOjE3MzkwMDEyMTd9.gIPey1epNElfPcLm1y_-I28RslZDg4_TQecZHwv8ngw


### GET ACCOUNT BY ACCOUNT NUMBER
GET http://localhost:5000/account/accountNumber/1234569
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YTZmZjcxZWJjZmRmMmIzNzAzYzllNiIsInVzZXJuYW1lIjoibGVuaW4zIiwiaWF0IjoxNzM4OTk3NjE3LCJleHAiOjE3MzkwMDEyMTd9.gIPey1epNElfPcLm1y_-I28RslZDg4_TQecZHwv8ngw


### GET ACCOUNT BY USERNAME
GET http://localhost:5000/account/username/P3
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YTZmZjcxZWJjZmRmMmIzNzAzYzllNiIsInVzZXJuYW1lIjoibGVuaW4zIiwiaWF0IjoxNzM4OTk3NjE3LCJleHAiOjE3MzkwMDEyMTd9.gIPey1epNElfPcLm1y_-I28RslZDg4_TQecZHwv8ngw


########################################## CARD ###############################################################

### ADD CARD
POST http://localhost:5000/card/
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YTc2MWI1ZjEzMjQyMjk1MDA2ZGFiZCIsInVzZXJuYW1lIjoic2VsdmFfMSIsImlhdCI6MTczOTAyMjc3NCwiZXhwIjoxNzM5MDI2Mzc0fQ.q7izjqSlqrvjifejBFQpz8KUxLNkseY_GT13XU-fHXE


{
    "cardNumber": 2321237833016,
    "cvv": 930,
    "expiry": "04/29",
    "status": "active",
    "accountNumber": 845000
}

### GET ALL CARD
GET http://localhost:5000/card/
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YTc3MDE0YjY1MDIxMTUxYzY1ZDUzOSIsInVzZXJuYW1lIjoiZGhhcnVuXzEiLCJpYXQiOjE3MzkwMjY0NTIsImV4cCI6MTczOTAzMDA1Mn0.A-6WnPcoRadccy0MeJ6uoF5cDB2Mo2286E0-A_jD1vM
### GET CARD BY ID
GET http://localhost:5000/card/67a612651bf47673cc077307
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YTZmZjcxZWJjZmRmMmIzNzAzYzllNiIsInVzZXJuYW1lIjoibGVuaW4zIiwiaWF0IjoxNzM4OTk3NjE3LCJleHAiOjE3MzkwMDEyMTd9.gIPey1epNElfPcLm1y_-I28RslZDg4_TQecZHwv8ngw


### UPDATE CARD BY ID
PUT http://localhost:5000/card/67a612651bf47673cc077307
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YTZmZjcxZWJjZmRmMmIzNzAzYzllNiIsInVzZXJuYW1lIjoibGVuaW4zIiwiaWF0IjoxNzM4OTk3NjE3LCJleHAiOjE3MzkwMDEyMTd9.gIPey1epNElfPcLm1y_-I28RslZDg4_TQecZHwv8ngw


{
    "cardNumber": 123456789016,
    "cvv": 456,
    "expiry": "12/28",
    "status": "block",
    "accountNumber": 1234569
}

### DELETE CARD BY ID
DELETE http://localhost:5000/card/67a612651bf47673cc077307
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YTZmZjcxZWJjZmRmMmIzNzAzYzllNiIsInVzZXJuYW1lIjoibGVuaW4zIiwiaWF0IjoxNzM4OTk3NjE3LCJleHAiOjE3MzkwMDEyMTd9.gIPey1epNElfPcLm1y_-I28RslZDg4_TQecZHwv8ngw


### GET CARD BY ACCOUNT NUMBER 

GET http://localhost:5000/card/accountNumber/777000
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YTZmZjcxZWJjZmRmMmIzNzAzYzllNiIsInVzZXJuYW1lIjoibGVuaW4zIiwiaWF0IjoxNzM4OTk3NjE3LCJleHAiOjE3MzkwMDEyMTd9.gIPey1epNElfPcLm1y_-I28RslZDg4_TQecZHwv8ngw