### CREATE a Bank Account
POST http://localhost:4000/account
Content-Type: application/json

{
    "username": "P3",
    "accountNumber": 1234569,
    "accountBalance": 6000,
    "accountStatus": "active"
}

### GET All Bank Accounts
GET http://localhost:4000/account

### GET a Bank Account by ID
GET http://localhost:4000/account/65b12345abcd67890ef12345

### UPDATE a Bank Account
PUT http://localhost:4000/account/65b12345abcd67890ef12345
Content-Type: application/json

{
    "accountBalance": 7000
}

### DELETE a Bank Account
DELETE http://localhost:4000/account/65b12345abcd67890ef12345

### GET Bank Account by Account Number
GET http://localhost:4000/accountNumber/123456789

### GET Bank Account by USERNAME
GET http://localhost:4000/username/dpz

### GET Bank Account by USERNAME
GET http://localhost:4000/accountCard/

