### ADD CARD
POST http://localhost:7000/
Content-Type: application/json

{
    "cardNumber": 123456789016,
    "cvv": 456,
    "expiry": "12/28",
    "status": "active",
    "accountNumber": 1234569
}

### GET ALL CARD
GET http://localhost:7000/

### GET CARD BY ID
GET http://localhost:7000/67a5ca9f0bc3009fb71db020

### UPDATE CARD BY ID
PUT http://localhost:7000/67a5ca9f0bc3009fb71db020
Content-Type: application/json

{
    "cardNumber": 123456789016,
    "cvv": 456,
    "expiry": "12/28",
    "status": "block",
    "accountNumber": 1234569
}

### DELETE CARD BY ID
DELETE http://localhost:7000/67a5ca9f0bc3009fb71db020

### GET CARD BY ACCOUNT NUMBER 

GET http://localhost:7000/accountNumber/1234569
